### ISSUE TITLE
Skip plugin execution if BUILDKITE_COMMAND_EXIT_STATUS != 0

### ISSUE THREAD

**Issue by vgrigoruk** [joscha/codecov-buildkite-plugin#6]
It makes no sense to upload coverage reports in case of failed tests. Adding something like this at the beginning of the script should help: 
```
if [ ${BUILDKITE_COMMAND_EXIT_STATUS} -ne 0 ]; then
  echo "~~~ codecov report upload is skipped because step returned ${BUILDKITE_COMMAND_EXIT_STATUS}"
  exit 0
fi
```

Alternatively, config option could be also introduced to toggle this behavior (however I still believe the default should be to skip upload in case of failed command).

**Comment by joscha** [comment]
Some companies don't use coverage as a fixed number you have to reach in order to get your changes integrated into the mainline but purely as feedback for the developer so they can see which code paths might not be covered. For this reason uploading in the case of failure still makes sense I believe, but I am happy to accept a PR with a config option changing the default that allows you to skip the plugin in case of failure.
